name: NodeSeek 自动签到评论加鸡腿

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # UTC 16:00，即北京时间 00:00

jobs:
  run-nodeseek-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Install Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver xvfb
          echo "Chrome version:"
          chromium-browser --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          HEADLESS: "true"
        run: |
          python nodeseek_daily.py